# Pandas

Ejemplos de captación de un dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://github.com/hchocobar/ds-datasets/blob/main/data/raw/AB_NYC_2019.csv')

KeyboardInterrupt:

In [6]:
url = "https://raw.githubusercontent.com/hchocobar/ds-datasets/main/data/raw/financiero-producto.csv"

df = pd.read_csv(url)
df.head()

,,,Product,ProductID,Familia,CategoriaPrecio,Manufacturing Price Std,PrecioListaReferencia,MargenTeoricoPct,EstadoProducto
Amarilla,PRD006,Mountain,Premium,'$260,00','$350,00','25,7%',Activo
Carretera,PRD001,Road,Entry,'$3,00','$20,00','85,0%',Activo
Montana,PRD002,Road,Entry,'$5,00','$20,00','75,0%',Activo
Paseo,PRD003,Urban,Standard,'$10,00','$20,00','50,0%',Activo
Velo,PRD004,Touring,Premium,'$120,00','$125,00','4,0%',Activo

In [8]:
file_csv = '../data/raw/Localidades.csv'
df = pd.read_csv(file_csv)
df

     A  AA       CANELONES
0    A  AO         JOANICO
1    A  BA     SANTA LUCIA
2    A  BO         EMPALME
3    A  CA       CERRILLOS
4    A  CO  AGUAS CORRIENT
..  ..  ..             ...
451  R  AW    PASO D.CERRO
452  R  AX           IPORA
453  R  AY       CARAGUATA
454  R  AZ     PIEDRA SOLA
455  V  AA      MONTEVIDEO

[456 rows x 3 columns]